# Generated by Django 5.2.17 on 2026-09-27 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vacation', 'Vacances'), ('sick', 'Malade'), ('other', 'Absent')], max_length=10, verbose_name='motif')),
                ('note', models.CharField(blank=True, max_length=80, verbose_name='précision')),
                ('start_date', models.DateField(verbose_name='du')),
                ('end_date', models.DateField(verbose_name='au')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='families.family')),
                ('person', models.ForeignKey(blank=True, help_text='Vide = toute la famille.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='families.person', verbose_name='qui')),
            ],
            options={
                'verbose_name': 'absence',
                'ordering': ['start_date', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='absence_dates_ordered')],
            },
        ),
    ]
