# Generated by Django 5.2.17 on 2026-09-27 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='intitulé')),
                ('period', models.CharField(choices=[('morning', 'Matin'), ('noon', 'Midi'), ('evening', 'Soir')], max_length=10, verbose_name='période')),
                ('weekdays', models.PositiveSmallIntegerField(default=127, help_text='Masque de bits, bit 0 = lundi.', verbose_name='jours')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='families.person')),
            ],
            options={
                'verbose_name': 'tâche',
                'ordering': ['position', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, help_text="Vide si coché depuis l'affichage partagé.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tasks.task')),
            ],
            options={
                'verbose_name': 'validation',
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('weekdays__gt', 0), ('weekdays__lte', 127)), name='task_weekdays_valid'),
        ),
        migrations.AddConstraint(
            model_name='taskcompletion',
            constraint=models.UniqueConstraint(fields=('task', 'date'), name='unique_completion_per_day'),
        ),
    ]
