# Generated by Django 5.2.17 on 2026-09-28 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_alter_familymembership_role_alter_person_role'),
        ('tasks', '0002_task_date_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('finished', models.BooleanField(verbose_name="devoirs finis à l'étude")),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_checks', to='families.person')),
            ],
            options={
                'verbose_name': "devoirs à l'étude",
                'verbose_name_plural': "devoirs à l'étude",
                'constraints': [models.UniqueConstraint(fields=('person', 'date'), name='unique_homework_check')],
            },
        ),
    ]
