# Generated by Django 5.2.17 on 2026-09-27 21:38

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_name',
            field=models.CharField(blank=True, help_text="Identifiant court de connexion, à la place de l'e-mail.", max_length=30, null=True, unique=True, validators=[apps.accounts.models.validate_login_name], verbose_name='identifiant'),
        ),
    ]
