# Generated by Django 5.2.17 on 2026-09-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembership',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('child', 'Enfant'), ('display', 'Écran partagé')], max_length=10, verbose_name='rôle'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('child', 'Enfant'), ('display', 'Écran partagé')], max_length=10, verbose_name='rôle affiché'),
        ),
    ]
