# Generated by Django 5.2.17 on 2026-09-27 18:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(verbose_name='semaine (lundi)')),
                ('transferred_at', models.DateTimeField(auto_now=True)),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_transfer', to='families.family')),
            ],
            options={
                'verbose_name': 'transfert du menu',
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='article')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='quantité')),
                ('unit', models.CharField(choices=[('piece', 'pièce(s)'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('cl', 'cl'), ('l', 'l'), ('tbsp', 'c. à soupe'), ('tsp', 'c. à café'), ('pack', 'paquet(s)'), ('can', 'boîte(s)')], default='piece', max_length=5, verbose_name='unité')),
                ('origin', models.CharField(choices=[('menu', 'Menu de la semaine'), ('manual', 'Ajouté à la main')], default='manual', max_length=6)),
                ('status', models.CharField(choices=[('to_buy', 'À acheter'), ('bought', 'Acheté'), ('at_home', 'Déjà à la maison')], default='to_buy', max_length=7)),
                ('recurring', models.BooleanField(default=False, help_text='Reste sur la liste quand on retire les achats.', verbose_name='revient chaque semaine')),
                ('merge_key', models.CharField(blank=True, max_length=120)),
                ('recipes', models.CharField(blank=True, max_length=200, verbose_name='pour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='families.family')),
            ],
            options={
                'verbose_name': 'article de courses',
                'verbose_name_plural': 'articles de courses',
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('origin', 'menu')), fields=('family', 'merge_key'), name='unique_menu_shopping_item'), models.CheckConstraint(condition=models.Q(('origin', 'manual'), ('recurring', False), _connector='OR'), name='shopping_recurring_only_manual'), models.CheckConstraint(condition=models.Q(('quantity__isnull', True), ('quantity__gt', 0), _connector='OR'), name='shopping_quantity_positive')],
            },
        ),
    ]
