# Generated by Django 5.2.17 on 2026-09-27 18:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('prep_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='préparation (minutes)')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favori')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='families.family')),
            ],
            options={
                'verbose_name': 'recette',
                'ordering': ['-is_favorite', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MealSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('lunch', 'Déjeuner'), ('dinner', 'Dîner')], max_length=6, verbose_name='repas')),
                ('kind', models.CharField(choices=[('recipe', 'Une recette'), ('leftovers', 'Restes'), ('outside', 'Extérieur'), ('free', 'Autre')], max_length=10, verbose_name='au menu')),
                ('note', models.CharField(blank=True, help_text='Restes du couscous, chez mamie, pizza…', max_length=80, verbose_name='précision')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_slots', to='families.family')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_slots', to='meals.recipe', verbose_name='recette')),
            ],
            options={
                'verbose_name': 'repas du menu',
                'verbose_name_plural': 'menu',
                'ordering': ['date', '-meal'],
                'constraints': [models.UniqueConstraint(fields=('family', 'date', 'meal'), name='unique_meal_slot'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'recipe'), ('recipe__isnull', False)), models.Q(models.Q(('kind', 'recipe'), _negated=True), ('recipe__isnull', True)), _connector='OR'), name='meal_slot_recipe_iff_kind_recipe')],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='ingrédient')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='quantité')),
                ('unit', models.CharField(choices=[('piece', 'pièce(s)'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('cl', 'cl'), ('l', 'l'), ('tbsp', 'c. à soupe'), ('tsp', 'c. à café'), ('pack', 'paquet(s)'), ('can', 'boîte(s)')], default='piece', max_length=5, verbose_name='unité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='meals.recipe')),
            ],
            options={
                'verbose_name': 'ingrédient',
                'ordering': ['created_at', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__isnull', True), ('quantity__gt', 0), _connector='OR'), name='ingredient_quantity_positive')],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='n°')),
                ('text', models.CharField(max_length=500, verbose_name='étape')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='meals.recipe')),
            ],
            options={
                'verbose_name': 'étape',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('recipe', 'position'), name='unique_recipe_step')],
            },
        ),
    ]
