# Generated by Django 5.2.17 on 2026-09-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDayOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch', models.CharField(choices=[('canteen', 'Cantine'), ('packed', 'Sandwich (APC)'), ('other', 'Autre'), ('none', "Pas d'école")], max_length=10, verbose_name='midi')),
                ('lunch_note', models.CharField(blank=True, help_text='Pour « Autre » : chez mamie, à la maison…', max_length=60, verbose_name='précision')),
                ('study', models.BooleanField(default=False, verbose_name='étude le soir')),
                ('date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_overrides', to='families.person')),
            ],
            options={
                'verbose_name': "exception d'école",
                'ordering': ['date', 'person'],
                'constraints': [models.UniqueConstraint(fields=('person', 'date'), name='unique_school_override')],
            },
        ),
        migrations.CreateModel(
            name='SchoolDaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch', models.CharField(choices=[('canteen', 'Cantine'), ('packed', 'Sandwich (APC)'), ('other', 'Autre'), ('none', "Pas d'école")], max_length=10, verbose_name='midi')),
                ('lunch_note', models.CharField(blank=True, help_text='Pour « Autre » : chez mamie, à la maison…', max_length=60, verbose_name='précision')),
                ('study', models.BooleanField(default=False, verbose_name='étude le soir')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='0 = lundi.', verbose_name='jour')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_schedules', to='families.person')),
            ],
            options={
                'verbose_name': "journée d'école type",
                'verbose_name_plural': "semaine d'école type",
                'ordering': ['person', 'weekday'],
                'constraints': [models.UniqueConstraint(fields=('person', 'weekday'), name='unique_school_weekday'), models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='school_weekday_valid')],
            },
        ),
    ]
