# Generated by Django 5.2.17 on 2026-09-27 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaturdayActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='activité')),
                ('season', models.CharField(choices=[('all', 'Toutes saisons'), ('spring', 'Printemps'), ('summer', 'Été'), ('autumn', 'Automne'), ('winter', 'Hiver')], default='all', max_length=10, verbose_name='saison')),
                ('place', models.CharField(choices=[('outing', 'Sortie'), ('home', 'Maison')], max_length=10, verbose_name='lieu')),
                ('is_free', models.BooleanField(default=True, verbose_name='gratuite')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='prix indicatif (€)')),
                ('star_cost', models.PositiveSmallIntegerField(default=0, help_text="0 = pas besoin d'étoiles. Sinon, payé par le pot commun des enfants.", verbose_name='coût en étoiles')),
                ('last_done_on', models.DateField(blank=True, null=True, verbose_name='dernière fois')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saturday_activities', to='families.family')),
            ],
            options={
                'verbose_name': 'activité du samedi',
                'verbose_name_plural': 'activités du samedi',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SaturdayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='samedi')),
                ('status', models.CharField(choices=[('drawing', 'Tirage en cours'), ('planned', 'Prévu'), ('done', 'Fait')], default='drawing', max_length=10)),
                ('activity_name', models.CharField(blank=True, help_text="Copie du nom : l'historique survit au catalogue.", max_length=80)),
                ('spins', models.PositiveSmallIntegerField(default=0, verbose_name='tirages effectués')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, help_text='Proposition en cours, puis activité validée.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='saturday.saturdayactivity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saturday_plans', to='families.family')),
            ],
            options={
                'verbose_name': 'samedi',
                'ordering': ['-date'],
            },
        ),
    ]
