# Generated by Django 5.2.17 on 2026-09-27 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saturday', '0001_initial'),
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saturdayplan',
            name='star_spend',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan', to='stars.starspend'),
        ),
        migrations.AddConstraint(
            model_name='saturdayplan',
            constraint=models.UniqueConstraint(fields=('family', 'date'), name='unique_plan_per_saturday'),
        ),
    ]
