# Generated by Django 5.2.17 on 2026-09-27 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='quoi')),
                ('start_time', models.TimeField(verbose_name='de')),
                ('end_time', models.TimeField(verbose_name='à')),
                ('weekdays', models.PositiveSmallIntegerField(default=127, verbose_name='jours')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='du')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='au')),
                ('location', models.CharField(blank=True, max_length=80, verbose_name='où')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='families.family')),
                ('people', models.ManyToManyField(blank=True, related_name='events', to='families.person', verbose_name='qui')),
            ],
            options={
                'verbose_name': 'rendez-vous',
                'verbose_name_plural': 'rendez-vous',
                'ordering': ['start_time', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='event_times_ordered'), models.CheckConstraint(condition=models.Q(('weekdays__gt', 0), ('weekdays__lte', 127)), name='event_weekdays_valid'), models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='event_dates_ordered')],
            },
        ),
    ]
