# Generated by Django 5.2.17 on 2026-09-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('date', models.DateField(verbose_name='date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrations', to='families.family')),
            ],
            options={
                'verbose_name': 'fête',
                'ordering': ['date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CelebrationTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=120, verbose_name='à faire')),
                ('done', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebration_todos', to='families.person', verbose_name="qui s'en occupe")),
                ('celebration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='celebrations.celebration')),
            ],
            options={
                'verbose_name': 'préparatif',
                'ordering': ['created_at', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GiftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.CharField(max_length=120, verbose_name='cadeau')),
                ('recipient_name', models.CharField(blank=True, max_length=60, verbose_name='pour (autre)')),
                ('buyer_name', models.CharField(blank=True, max_length=60, verbose_name='apporté par (autre)')),
                ('done', models.BooleanField(default=False, verbose_name='acheté')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts_bought', to='families.person', verbose_name='apporté par')),
                ('celebration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='celebrations.celebration')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts_received', to='families.person', verbose_name='pour')),
            ],
            options={
                'verbose_name': 'cadeau',
                'ordering': ['created_at', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120, verbose_name='recette')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('celebration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='celebrations.celebration')),
            ],
            options={
                'verbose_name': 'idée de recette',
                'verbose_name_plural': 'idées de recettes',
                'ordering': ['created_at', 'pk'],
                'abstract': False,
            },
        ),
    ]
