# Generated by Django 5.2.17 on 2026-09-27 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebration',
            name='previous',
            field=models.OneToOneField(blank=True, help_text="Occurrence de l'année précédente dont celle-ci est la suite.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_occurrence', to='celebrations.celebration'),
        ),
        migrations.AddField(
            model_name='celebration',
            name='recurs_yearly',
            field=models.BooleanField(default=False, help_text="Anniversaire… (pas l'Aïd, dont la date change chaque année).", verbose_name='chaque année'),
        ),
    ]
