# Generated by Django 5.2.17 on 2026-09-27 12:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdChore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='tâche')),
                ('weekdays', models.PositiveSmallIntegerField(default=127, verbose_name='jours')),
                ('interval_weeks', models.PositiveSmallIntegerField(choices=[(1, 'Chaque semaine'), (2, 'Une sur deux')], default=1, verbose_name='toutes les N semaines')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='à partir du')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_chores', to='families.person')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_chores', to='families.family')),
            ],
            options={
                'verbose_name': 'tâche de ménage',
                'verbose_name_plural': 'tâches de ménage',
                'ordering': ['title', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ChoreCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='household.householdchore')),
            ],
            options={
                'verbose_name': 'ménage fait',
            },
        ),
        migrations.AddConstraint(
            model_name='householdchore',
            constraint=models.CheckConstraint(condition=models.Q(('weekdays__gt', 0), ('weekdays__lte', 127)), name='chore_weekdays_valid'),
        ),
        migrations.AddConstraint(
            model_name='householdchore',
            constraint=models.CheckConstraint(condition=models.Q(('interval_weeks__in', [1, 2])), name='chore_interval_valid'),
        ),
        migrations.AddConstraint(
            model_name='chorecompletion',
            constraint=models.UniqueConstraint(fields=('chore', 'date'), name='unique_chore_completion'),
        ),
    ]
