# Generated by Django 5.2.17 on 2026-09-28 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_alter_familymembership_role_alter_person_role'),
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreSwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(verbose_name='semaine du')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'échange de ménage',
                'verbose_name_plural': 'échanges de ménage',
            },
        ),
        migrations.AddField(
            model_name='householdchore',
            name='alternate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternate_household_chores', to='families.person', verbose_name='en alternance avec'),
        ),
        migrations.AddConstraint(
            model_name='householdchore',
            constraint=models.CheckConstraint(condition=models.Q(('alternate__isnull', True), models.Q(models.Q(('alternate', models.F('assignee')), _negated=True), ('interval_weeks', 1)), _connector='OR'), name='chore_alternate_valid'),
        ),
        migrations.AddField(
            model_name='choreswap',
            name='chore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='household.householdchore'),
        ),
        migrations.AddConstraint(
            model_name='choreswap',
            constraint=models.UniqueConstraint(fields=('chore', 'week'), name='unique_chore_swap_per_week'),
        ),
    ]
