# Generated by Django 5.2.17 on 2026-09-27 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=120, verbose_name='motif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_spends', to='families.family')),
            ],
            options={
                'verbose_name': "dépense d'étoiles",
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='StarDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_debits', to='families.person')),
                ('spend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='stars.starspend')),
            ],
            options={
                'verbose_name': 'contribution',
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('spend', 'person'), name='unique_debit_per_person'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='debit_positive')],
            },
        ),
    ]
