# Generated by Django 5.2.17 on 2026-09-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierCelebration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier_celebration', to='families.person')),
            ],
            options={
                'verbose_name': 'palier fêté',
            },
        ),
    ]
