# Generated by Django 5.2.17 on 2026-09-27 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('stars', '0002_tier_celebration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('celebrated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_stars', to='families.person')),
            ],
            options={
                'verbose_name': 'étoile du jour',
                'verbose_name_plural': 'étoiles du jour',
                'ordering': ['-date', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('person', 'date'), name='unique_day_star_per_person')],
            },
        ),
    ]
