# Generated by Django 5.2.17 on 2026-09-27 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('stars', '0003_day_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='étoiles')),
                ('reason', models.CharField(max_length=120, verbose_name='motif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='star_opening_balance', to='families.person')),
            ],
            options={
                'verbose_name': 'solde de départ',
                'verbose_name_plural': 'soldes de départ',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='opening_balance_positive')],
            },
        ),
    ]
